---
title: "Course Files"
output: github_document
---

<head>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>

<a href = "https://jbpost2.github.io/Improving-R-Programs/"><button type="button">Course Home</button></a>

Below you'll find the presentation files for the course and the exercises we'll do during the hands on sessions.

Note: You also have access to the source material at the [github repo](https://github.com/jbpost2/Improving-R-Programs).

We've also included links to materials to go further learning R at the bottom of the page!

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
<h2 class="intro-text text-center">

<center>

<strong>Presentation Files</strong>

</center>

</h2>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
::: {.row}
::: {style="width: 50%;float: left;"}
    <center>
      <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <a href="https://jbpost2.github.io/Improving-R-Programs/slides/LoopsVectorized.html#1" target = "_blank">
          <i class="fa fa-list fa-stack-1x fa-inverse"></i></a>
      </span>
      <a href="https://jbpost2.github.io/Improving-R-Programs/slides/LoopsVectorized.html#1" target = "_blank">
        <h4 class="service-heading">Streamlining R Code</h4>
      </a>
      <p class="text-muted">
          <a href="https://jbpost2.github.io/Improving-R-Programs/slides/LoopsVectorized.pdf" target = "download">PDF version</a>
        </p>
        </center>
:::

::: {style="width: 50%;float: right;"}
    <center>
      <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <a href="https://jbpost2.github.io/Improving-R-Programs/slides/Functions.html#1" target = "_blank">
          <i class="fa fa-list fa-stack-1x fa-inverse"></i></a>
      </span>
      <a href="https://jbpost2.github.io/Improving-R-Programs/slides/Functions.html#1" target = "_blank">
        <h4 class="service-heading">Functions</h4>
      </a>
      <p class="text-muted">
          <a href="https://jbpost2.github.io/Improving-R-Programs/slides/Functions.pdf" target = "download">PDF version</a> 
        </p>
    </center>
:::
:::

::: {style="content: \"\";   clear: both;   display: table;"}
:::

It may help to have just the R code from the slides so you can easily run the code without typing it out. Below you'll find .R scripts with just the R code from the notes (notice that there is some extra stuff as we often use R code to bring in images and things like that).

-   <a href = "https://raw.githubusercontent.com/jbpost2/Improving-R-Programs/master/slides/LoopsVectorized.R" target = "download"> Streamlining R Code</a>
-   <a href = "https://raw.githubusercontent.com/jbpost2/Improving-R-Programs/master/slides/Functions.R" target = "download"> Functions</a>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
<h2 class="intro-text text-center">

<center>

<strong>Exercises</strong>

</center>

</h2>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
#### Exercise Sets

##### Streamlining R Code

-   <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises1_Loops.html"> Exercises 1 - Loops</a> (Solutions: <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises1_Loops_Solutions.html"> HTML</a>, <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises1_Loops_Solutions.Rmd"> Rmd</a>)
-   <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises2_ifelse.html"> Exercises 2 - if else</a> (Solutions: <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises2_ifelse_Solutions.html"> HTML</a>, <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises2_ifelse_Solutions.Rmd"> Rmd</a>)
-   <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises3_apply.html"> Exercises 3 - apply</a> (Solutions: <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises3_apply_Solutions.html"> HTML</a>, <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises3_apply_Solutions.Rmd"> Rmd</a>)

##### Functions

-   <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises4_BasicFunctions.html"> Exercises 1 - Basic Functions</a> (Solutions: <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises4_BasicFunctions_Solutions.html"> HTML</a>, <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises4_BasicFunctions_Solutions.Rmd"> Rmd</a>)
-   <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises5_MoreFunctions.html"> Exercises 5 - More Functions</a> (Solutions: <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises5_MoreFunctions_Solutions.html"> HTML</a>, <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises5_MoreFunctions_Solutions.Rmd"> Rmd</a>)
-   <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises6_LastFunctions.html"> Exercises 6 - Last Functions</a> (Solutions: <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises6_LastFunctions_Solutions.html"> HTML</a>, <a href = "https://jbpost2.github.io/Improving-R-Programs/exercises/Exercises6_LastFunctions_Solutions.Rmd"> Rmd</a>)


```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
<h2 class="intro-text text-center">

<center>

<strong>Learning Resources</strong>

</center>

</h2>

```{=html}
<hr style="    border: 0;
    height: 2px;
    background: #333;
    background-image: linear-gradient(to right, #ccc, #333, #ccc);">
```
#### Cheat Sheets

::: {.row}
::: {style="width: 33%;float: left;"}
    <center>
            <span class="fa-stack fa-4x">
                <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <a href="https://github.com/jbpost2/Improving-R-Programs/raw/master/cheatsheets/rstudio-ide.pdf" target="_blank">
                      <i class="fa fa-building fa-stack-1x fa-inverse"></i></a>
            </span>
            <h4 class="service-heading">
                    RStudio IDE
            </h4>
        </center>
:::

::: {style="width: 33%;float: left;"}
    <center>
        <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-stack-2x text-primary"></i>
                <a href="https://github.com/jbpost2/Improving-R-Programs/raw/master/cheatsheets/base-r.pdf" target="_blank">
              <i class="fa fa-gears fa-stack-1x fa-inverse"></i></a>
        </span>
        <h4 class="service-heading">
                Base R
        </h4>
    </center>
:::

::: {style="width: 33%;float: left;"}
    <center>
        <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-stack-2x text-primary"></i>
                <a href="https://github.com/jbpost2/Improving-R-Programs/raw/master/cheatsheets/advancedR.pdf" target="_blank">
              <i class="fa fa-book fa-stack-1x fa-inverse"></i></a>
        </span>
        <h4 class="service-heading">
                Advanced R
        </h4>
    </center>
:::
:::

::: {style="content: \"\";   clear: both;   display: table;"}
:::

<hr>

#### Other Courses

Justin teaches the following three courses for [Data Matters](https://datamatters.org/), a week-long series of one and two-day courses aimed at students and professionals in business, research, and government.

<hr>

<h4>

<a href = "https://jbpost2.github.io/Basics-of-R-for-Data-Science-and-Statistics/" target = "_blank">Basics of R for Data Science and Statistics</a>

</h4>

The course provides a modern introduction to the R through the extremely popular suite of packages called the tidyverse. A rough outline is given below:

Day 1:

-   Basics of how R stores data

-   R Packages and the tidyverse

-   Reading data from common formats into R (readr package)

-   Using R Markdown for reproducibility (rmarkdown and knitr packages)

-   Common data manipulations and creating new variables (dplyr package)

Day 2:

-   Reshaping data for summarizing and modeling (tidyr package)

-   Types of data and numeric summaries (including across groups)

-   Creating publication ready graphs (ggplot2 package)

<hr>

<h4>

<a href = "https://jbpost2.github.io/Improving-R-Programs/" target = "_blank">Improving R Programs</a>

</h4>

The course provides a brief overview of R data structures followed by the following topics:

-   Loops in R

-   Vectorized functions (apply family of functions)

-   How R functions work

-   Function writing

<hr>

<h4>

<a href = "https://jbpost2.github.io/R-for-Automating-Workflow-Sharing-Work/" target = "_blank">R for Automating Workflow & Sharing Work</a>

</h4>

Students will learn about the following topics:

-   The R Markdown language

-   How to automate reports with R Markdown

-   Use of git and github for collaboration and version control

-   Basic creation of websites through Markdown and github

-   R Shiny web apps

<hr>

<h4>

<a href = "https://adv-r.hadley.nz/" target = "_blank">Advanced R Book</a>

</h4>

The book is designed primarily for R users who want to improve their programming skills and understanding of the language. It should also be useful for programmers coming to R from other languages, as help you to understand why R works the way it does.

<hr>

<br>

<a href = "https://jbpost2.github.io/Improving-R-Programs/"><button type="button">Course Home</button></a>
