---
title: "Exercises 2 - if else Solutions"
output:
  github_document
---

#We'll use the built-in 'CO2' data set. Write R code to do the following:

#1. Suppose we want to create a "group" indicator variable that tells us which Type*Treatment group we are in (i.e Quebec-nonchilled, Quebec-chilled, Mississippi-nonchilled, Mississippi-chilled, group 1, 2, 3, 4, respectively). Use ifelse to create this new variable and add it to the data set.
myCO2 <- tbl_df(CO2) %>% 
	mutate(group = ifelse((Type == "Quebec") & (Treatment == "nonchilled"), 
												1, ifelse((Type == "Quebec") & (Treatment == "chilled"), 2,
																	ifelse((Type == "Mississippi") & (Treatment == "nonchilled"), 3,
																				 ifelse((Type == "Mississippi") & (Treatment == "chilled"), 4, 0)))))
																				 

4) FizzBuzz is a common programming problem <https://en.wikipedia.org/wiki/Fizz_buzz> used to practice if statements and division. 

> For our version, create a vector 'test_vec' of the numbers 1 to 50. Then apply the following rules using only `ifelse` statements:

- if the number is divisible by 3 replace it with "Fizz"
- if the number is divisible by 5, replace it with "Buzz"
- if the number is divisible by 15, replace it with "FizzBuzz"
- otherwise, return the number

```{r}
test_vec <- 1:50

ifelse(test_vec %% 15 == 0, "FizzBuzz", 
       ifelse(test_vec %% 3 == 0, "Fizz", 
              ifelse(test_vec %% 5 ==0, "Buzz", test_vec)
              )
      )
```


<hr>

<br>

<a href = "https://jbpost2.github.io/Improving-R-Programs/CourseFiles.html"><button type="button">Course Files Page</button></a>

